---
title: "Flight_Delay_Prediction_using_R"
author: "Joseph Vinay Kumar POLANKI"
date: "`r Sys.Date()`"
output: word_document
---



# Setting up the knitr file

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

## Abstract



## Research Questions


## DATA
setting working directory to avoid errors while saving binary files

```{r echo=TRUE}
setwd("G:/My Drive/CIS 663 R programming/ATC_R_Project/DATA")
```


##Loading DATA into rmd file from drive.

```{r Loading_Data, echo=TRUE}
#Loading and Inspecting the DATA
install.packages("readr")
library(readr)
Flight_DATA <- read.csv("G:/My Drive/CIS 663 R programming/ATC_R_Project/DATA/air_traffic_main_Data.csv", header = TRUE, stringsAsFactors = FALSE)

```

## Viewing first and last few rows.

```{r  Viewing_Data, echo = FALSE}
head(Flight_DATA)
tail(Flight_DATA)
```


```{r summaries, echo = TRUE }

is.na(Flight_DATA)

summary(Flight_DATA)

grouping(Flight_DATA$month)

```


```{r, echo=TRUE}

v <- c(Flight_DATA$arr_flights)




```


``` {}

```










